# Thinking Big: Data Tables {#data-tables}

Data frames are core elements for data handling in R.  However, the
suffer from several limitations.  One of the major issue with data
frames is that they are memory hungry and slow.  This is not an issue
when working with relatively small datasets (say, up to 100,000
rows).  However, when your dataset size exceed gigabytes, dataframes
may be infeasibly slow and too memory hungry.


## Background: Passing By Value And Passing By Reference

R is (mostly) a pass-by-value language.  This means that when you
modify the data, at every step a new copy of the complete modified
object is created, stored in memory, and the former object is freed
(carbage-collected) if not in use any more.

The main advantage of this approach is consistency: we have the
guarantee that functions do not modify their inputs.  However, in case
of large objects, copying may be slow, and even more, it requires
at least twice as much memory before the old object is freed.  In case
of more complex process pipelines, the memory consumption may be even more
than twice of the size of the original object.

Data tables implement a number of pass-by-reference functions.  In
pass-by-reference, the function is not given a fresh copy of the
inputs, but is instead told where is the object in memory.  Instead of
copying gigabytes of data, only a single tiny memory pointer is
passed.  But this also means the function now is accessing and
modifying the original object, not a copy of it.  This may sometimes
lead to bugs and unexpected behavior, but professional use of
pass-by-reference approach may improve the speed and lower the memory
footprint substantially.


## Data Tables: intro

Data tables and most of the related goodies live in _data.table_
library.

Data tables as designed to be largely a replacement to data frames.
The syntax is similar and they are largely replaceable.  For instance,
we can create and play with a data table as
```{r}
library(data.table)
dt <- data.table(id=1:5, x=rnorm(5), y=runif(5))
dt
```
The result looks almost identical to a similar data frame (the only
difference are the colons after the row numbers).  Behind the scenes
these objects are almost identical too--both objects are lists of
vectors.  This structural similarity largely allows to use data tables
as drop-in replacements for dataframes.



look like data frames


## Indexing:

[i, j, by]

compare with dplyr


## Create variables by reference

:=

## keys

Sort in advance

fast lookups


## joins, melt
